# Builder

FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server main.go


# Runtime

FROM alpine:3.22
RUN apk add --no-cache proxychains-ng curl
COPY --from=builder /app/server /server
EXPOSE 8080
CMD ["/server"]
